#!/bin/bash

# M O M E N T U M

# Usage: _momentum -t TEXTTOPLOT -v VERSION -l LINE -p
# Plot text in circle at set size using vpype and axicli

# arguments

while getopts t:v:l:p opts; do
   case ${opts} in
      t) TEXT=${OPTARG} ;;
      v) VERSION=${OPTARG} ;;
      l) LINE=${OPTARG} ;;
      p) PLOT=true ;;
   esac
done

# echo $TEXT
# echo $VERSION
# echo $PLOT

# VERSION 0 --> logo  ** flag not implemented todo **
# VERSION 1 --> poster 1
# VERSION 2 --> poster 2

# init

ORIGIN="0 0"
CMD='vpype '
OUT='out.svg'

if [ "$VERSION" == "1" ]; then

    Y=0
    # SIZE=50       # MOMENTUM LOGO
    SIZE=284        # MOMENTUM POSTER 1 

    # text

    if [[ -z "$TEXT" ]]; then
        case $LINE in
            0) TEXT='MOMENTUM' ;;
            1) TEXT='ALEXANDRAWAIERSTALL' ;;
            2) TEXT='DISCOTECAFLAMINGSTAR' ;;
            3) TEXT='OCTOBER1314152023' ;;
            4) TEXT='DAILY12TO4PM' ;;
        esac
    fi

    # calculate circle

    # size of circle (X) based on CHARS
    # so always the same size type and same spacing
    # but circle changes size
    # height of each letter should be type size
    # add them all up and get cicrumfrence
    # from circumfrence, get radius
    # C = 2 * PI * R, R = C / PI

    CHARS=${#TEXT}
    ROTATE=-`bc -l <<< "360 / $CHARS"`
    PI=3.14159265358979323846264338327950288419716939937510
    SIZE_ADJ=41      # adjust letterspacing with $RADIUS    
    CIRCUM=`bc -l <<< "($SIZE - $SIZE_ADJ) * $CHARS"`
    RADIUS=`bc -l <<< "$CIRCUM / (2 * $PI)"`
    X=$RADIUS

    foo=$TEXT
    for (( i=0; i<${#foo}; i++ )); do
        echo "${foo:$i:1}"
        TEXT="${foo:$i:1}"
        CMD+='text --align center --size '$SIZE' --position '$X' '$Y' "'$TEXT'" rotate --origin 0 0 -- '$ROTATE' '
    done

    # layout

    # CMD+='layout --fit-to-margins 0.25in --align left --landscape 11x17in '     #ALEXANDRAWEIRSTALL
    # CMD+='layout --fit-to-margins 0.25in --align left --landscape 11x17in '     #DISCOTECAFLAMINGSTAR
    # CMD+='layout --fit-to-margins 1.5in --align left --landscape 11x17in '     #OCTOBER1314152023
    # CMD+='layout --fit-to-margins 3.0in --align left --landscape 11x17in '     #DAILY12TO4PM

fi

if [ "$VERSION" == "2" ]; then

    echo 'version '$VERSION
    SIZE=284

    if [ "$LINE" == "0" ]; then
        TEXT='HAUSCHKA'
        W=6in
        H=16in
        CMD+='text --size '$SIZE' "'$TEXT'" '
    fi
    if [ "$LINE" == "1" ]; then
        TEXT='FEBRUARY2420241PM'
        W=9in
        H=7in
        CMD+='text --size '$SIZE' "'$TEXT'" '
    fi    
    if [ "$LINE" == "2" ]; then
        TEXT='YINGYUNCHENG,'
        TEXT2='SCOTTJENNINGS'
        X=200
        W=7in
        H=9in
        HH=9

        # still a mess in here ** fix **

        Y2=`echo "scale=2 ; $HH / 4.5" | bc`in

        CMD+='text --align left --size '$SIZE' --position $X '0' "'$TEXT'" '
        CMD+='text --align left --size '$SIZE' --position $X '$Y2' "'$TEXT2'" '
    fi

    CMD+='scaleto --fit-dimensions '$W' '$H' '
    CMD+='layout --align right --valign top --fit-to-margins 0.25in tabloid '
fi

# svg output

CMD+='linemerge '
CMD+='write '$OUT

# print

echo $CHARS
echo $CIRCUM
echo $RADIUS
eval $CMD
open out.svg
# open -a Safari out.svg
if [[ -n "$PLOT" ]]; then
    echo "PLOTTING ..."
    axicli out.svg --model 2 --progress
fi
exit
